// <auto-generated />
using System;
using BGame.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BGame.Migrations
{
    [DbContext(typeof(BGameDbContext))]
    [Migration("20181209202053_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BGame.Models.Comment", b =>
                {
                    b.Property<int>("commentID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameID");

                    b.Property<int?>("GameItemId");

                    b.Property<int>("UserID");

                    b.Property<string>("commentContent");

                    b.Property<string>("commenterName");

                    b.Property<string>("commenterProfile");

                    b.Property<DateTime>("date");

                    b.HasKey("commentID");

                    b.HasIndex("GameItemId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("BGame.Models.GameItem", b =>
                {
                    b.Property<int>("GameItemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<string>("Description");

                    b.Property<string>("Image");

                    b.Property<string>("Name");

                    b.Property<int>("Players");

                    b.Property<float>("Price");

                    b.Property<int>("Quantity");

                    b.Property<int>("UserId");

                    b.HasKey("GameItemId");

                    b.ToTable("GameItems");
                });

            modelBuilder.Entity("BGame.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<string>("Line1")
                        .IsRequired();

                    b.Property<string>("Line2");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("date");

                    b.Property<bool>("isCompleted");

                    b.HasKey("OrderID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BGame.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GameItemId");

                    b.Property<int>("OrderID");

                    b.Property<int>("Quantity");

                    b.Property<DateTime>("date");

                    b.HasKey("OrderItemID");

                    b.HasIndex("GameItemId");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("BGame.Models.Comment", b =>
                {
                    b.HasOne("BGame.Models.GameItem")
                        .WithMany("Comments")
                        .HasForeignKey("GameItemId");
                });

            modelBuilder.Entity("BGame.Models.OrderItem", b =>
                {
                    b.HasOne("BGame.Models.GameItem", "GameItem")
                        .WithMany()
                        .HasForeignKey("GameItemId");

                    b.HasOne("BGame.Models.Order")
                        .WithMany("OrderItemList")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
